erase

diff --git a/bin/pgo b/bin/pgo
--- a/bin/pgo
+++ b/bin/pgo
@@ -416,6 +416,7 @@ function apply() {
       printf '%s\n' "public_instance_password_windows1 = \"$(terraform output -raw public_instance_password_windows1)\""
       ;;
     kind)
+      lock kind
       cd ${ONEPATH}/awsone/6-cluster-kind
       terraform apply -auto-approve
       ;;
@@ -746,6 +747,7 @@ function destroy() {
     kind)
       cd ${ONEPATH}/awsone/6-cluster-kind
       terraform destroy -auto-approve
+      unlock kind
       ;;
   esac
 }
@@ -1142,6 +1144,131 @@ function colima-service() {
   esac
 }
 
+#######################################
+# Cleanup Terraform state and modules
+# Globals:
+#   None
+# Arguments:
+#   Configuration name or all
+# Outputs:
+#   None
+#######################################
+function erase() {
+
+  telemetry "cleanup" $1
+
+  case $1 in
+    nw|network|all)
+      if ! checklock nw; then
+        cd ${ONEPATH}/awsone/2-network
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+      fi
+      ;;&
+    ec2|instances|all)
+      if ! checklock ec2; then
+        cd ${ONEPATH}/awsone/3-instances
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+      fi
+      ;;&
+    eks|eks-ec2|all)
+      if ! checklock eks-ec2; then
+        cd ${ONEPATH}/awsone/4-cluster-eks-ec2
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+        cd ${ONEPATH}/awsone/8-cluster-eks-ec2-deployments
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+      fi
+      ;;&
+    eks-fg|all)
+      if ! checklock eks-fg; then
+        cd ${ONEPATH}/awsone/4-cluster-eks-fargate
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+        cd ${ONEPATH}/awsone/8-cluster-eks-fargate-deployments
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+      fi
+      ;;&
+    aks|all)
+      if ! checklock aks; then
+        cd ${ONEPATH}/azone/4-cluster-aks
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+        cd ${ONEPATH}/azone/8-cluster-aks-deployments
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+      fi
+      ;;&
+    ecs|all)
+      if ! checklock ecs; then
+        cd ${ONEPATH}/awsone/5-cluster-ecs
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+      fi
+      ;;&
+    scenarios|scenarios-ec2|all)
+      if ! checklock scenarios-ec2; then
+        cd ${ONEPATH}/awsone/7-scenarios-ec2
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+      fi
+      ;;&
+    scenarios-fg|all)
+      if ! checklock scenarios-fg; then
+        cd ${ONEPATH}/awsone/7-scenarios-fargate
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+      fi
+      ;;&
+    scenarios-aks|all)
+      if ! checklock scenarios-aks; then
+        cd ${ONEPATH}/azone/7-scenarios-aks
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+      fi
+      ;;&
+    dsm|deepsecurity|all)
+      if ! checklock dsm; then
+        cd ${ONEPATH}/awsone/9-deep-security
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+      fi
+      ;;&
+    dsw|all)
+      if ! checklock dsm; then
+        cd ${ONEPATH}/awsone/9-deep-security-workload
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+      fi
+      ;;&
+    kind|all)
+      if ! checklock kind; then
+        cd ${ONEPATH}/awsone/6-cluster-kind
+        rm -rf .terraform
+        rm -f .terraform.lock.hcl
+        rm -f terraform.tfstate*
+      fi
+      ;;
+  esac
+}
+
 function helpcmd() {
 
   printf '%s\n' "Usage: pgo -<command> <configuration> ..."
@@ -1160,6 +1287,7 @@ function helpcmd() {
   printf '%s\n' "  -d --destroy  Destroy previously-created configuration"
   printf '%s\n' "  -o --output   Show output values"
   printf '%s\n' "  -s --state    Show the current state"
+  printf '%s\n' "  -E --erase    Cleanup Terraform state and modules"
   printf '%s\n' "  -h --help     Show this help"
   printf '%s\n' ""
   printf '%s\n' "Other commands:"
@@ -1204,7 +1332,7 @@ if is_darwin; then
 
   eval set -- "$TEMP"
 else
-  TEMP=$(getopt -o ci:a:ld:o:s:S:v:uh --long config,init:,apply:,list,destroy:,output:,state:,show:,validate:,updateip,help -- "$@")
+  TEMP=$(getopt -o ci:a:ld:o:s:S:v:uhE: --long config,init:,apply:,list,destroy:,output:,state:,show:,validate:,updateip,help,erase: -- "$@")
   if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi
 
   eval set -- "$TEMP"
@@ -1232,6 +1360,7 @@ while true; do
     -u | --updateip ) update_ip; break ;;
     -h | --help ) helpcmd; break ;;
     -C | --colima ) colima-service $2; shift 2 ;;
+    -E | --erase ) erase $2; shift 2 ;;
     -- ) shift; break ;;
     * ) break ;;
   esac
